// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdFfQx3AfHj2VTmhVJSTaWSC5R3p0Uxws',
    appId: '1:117970896385:web:14002f2f9161fa43f9a200',
    messagingSenderId: '117970896385',
    projectId: 'nexus-68994',
    authDomain: 'nexus-68994.firebaseapp.com',
    storageBucket: 'nexus-68994.firebasestorage.app',
    measurementId: 'G-N4W5DBMRQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG4_bLX-icRZkiGQaQb5Z2YADDML1cYlc',
    appId: '1:117970896385:android:c733acb279b383f3f9a200',
    messagingSenderId: '117970896385',
    projectId: 'nexus-68994',
    storageBucket: 'nexus-68994.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvVqvj3u8Vs5tY8Vv6jFTLWqlBMIeX5E',
    appId: '1:117970896385:ios:b065639710b63e86f9a200',
    messagingSenderId: '117970896385',
    projectId: 'nexus-68994',
    storageBucket: 'nexus-68994.firebasestorage.app',
    iosBundleId: 'com.example.nexus2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWvVqvj3u8Vs5tY8Vv6jFTLWqlBMIeX5E',
    appId: '1:117970896385:ios:b065639710b63e86f9a200',
    messagingSenderId: '117970896385',
    projectId: 'nexus-68994',
    storageBucket: 'nexus-68994.firebasestorage.app',
    iosBundleId: 'com.example.nexus2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdFfQx3AfHj2VTmhVJSTaWSC5R3p0Uxws',
    appId: '1:117970896385:web:513e3fe685a0578df9a200',
    messagingSenderId: '117970896385',
    projectId: 'nexus-68994',
    authDomain: 'nexus-68994.firebaseapp.com',
    storageBucket: 'nexus-68994.firebasestorage.app',
    measurementId: 'G-971RRZDWF4',
  );

}